# Generated by Django 5.2 on 2025-08-02 14:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(max_length=20)),
                ('game_param', django.contrib.postgres.fields.hstore.HStoreField()),
                ('game_score', models.IntegerField(default=0)),
                ('game_state', models.CharField(max_length=20)),
                ('submitted_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'game',
                'db_table': 'game',
            },
        ),
    ]
